# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=255, verbose_name='Url')),
                ('resultado', models.TextField(max_length=255, verbose_name='Resultado')),
            ],
        ),
    ]
