# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscas', '0003_auto_20180927_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Url'),
        ),
    ]
